import './generateAdjectives';
import './generateAdverbs';
import './generateConjunctions';
import './generateInterjections';
import './generateNouns';
import './generateNumbers';
import './generateParticles';
import './generatePronouns';
import './generateVerbs';
